#!/bin/bash

#set -x
#set -v

#TODO filter status files

# ' ' = unmodified
# M = modified
# A = added
# D = deleted
# R = renamed
# C = copied
# U = updated but unmerged

#    X          Y     Meaning
#    -------------------------------------------------
#              [MD]   not updated
#    M        [ MD]   updated in index
#    A        [ MD]   added to index
#    D         [ M]   deleted from index
#    R        [ MD]   renamed in index
#    C        [ MD]   copied in index
#    [MARC]           index and work tree matches
#    [ MARC]     M    work tree changed since index
#    [ MARC]     D    deleted in work tree
#    -------------------------------------------------
#    D           D    unmerged, both deleted
#    A           U    unmerged, added by us
#    U           D    unmerged, deleted by them
#    U           A    unmerged, added by them
#    D           U    unmerged, deleted by us
#    A           A    unmerged, both added
#    U           U    unmerged, both modified
#    -------------------------------------------------
#    ?           ?    untracked
#    !           !    ignored
#    -------------------------------------------------

#TODO: Options for seeing ignored files
#TODO: Options for filter results
#TODO: Options to move around dirs

QUIT="quit"
NORMAL_PROMPT=" files> "

PS3=$NORMAL_PROMPT
OLDIFS=$IFS
SELECT_IFS="
"

IFS=$SELECT_IFS
while(true)
do
select STATUSLINE in $(git status --porcelain) "$QUIT"
do
    IFS=$OLDIFS
    FILE=$(echo "$STATUSLINE" | cut -c4-)
    INDEX_STATUS=$(echo "$STATUSLINE" | cut -c1)
    WORKTREE_STATUS=$(echo "$STATUSLINE" | cut -c2)
    if [[ "$QUIT" =~ "$REPLY" ]] || [ "$FILE" == "$QUIT" ]
    then
        break
    fi

    if [ -d $FILE ]
    then
        echo "   listing files in ($FILE)"
        PS3=" dir> "
        select DIRFILE in $(ls -1 $FILE) "$QUIT"
        do
            if [[ "$QUIT" =~ "$REPLY" ]] || [ "$DIRFILE" == "$QUIT" ]
            then
                break
            fi
            less $FILE/$DIRFILE
        done
    else
        PS3=" action ($FILE)> "
        ACTIONS=()
        if [ "$INDEX_STATUS" == "M" ]
        then
            ACTIONS+=("checkout")
            ACTIONS+=("diff --cached")
            ACTIONS+=("reset")
        else
            if [ "$WORKTREE_STATUS" == "M" ]
            then
                ACTIONS+=("checkout")
                ACTIONS+=("diff")
                ACTIONS+=("add")
            elif [ "$WORKTREE_STATUS" == "?" ]
            then
                ACTIONS+=("add")
            elif [ "$WORKTREE_STATUS" == "!" ]
            then
                #TODO: Show ignore pattern causing this
                ACTIONS+=("show-ignore")
            fi
        fi
        select ACTION in "${ACTIONS[@]}" "$QUIT"
        do
            if [[ "$QUIT" =~ "$REPLY" ]] || [ "$ACTION" == "$QUIT" ]
            then
                break
            fi
            if [ "$ACTION" == "checkout" ] && [ "$INDEX_STATUS" == "M" ]
            then
                git reset $FILE
            fi
            git $ACTION $FILE
            if ! [[ "$ACTION" =~ "diff" ]]
            then
                break
            fi
        done
    fi
    PS3=$NORMAL_PROMPT
    IFS=$SELECT_IFS
    break
done
done
